### ISSUE TITLE
docker-compose not supported on Windows

### ISSUE THREAD

**Issue by msamblanet** [anvilresearch/connect-cli#29]
The current directions for setting up connect do not work under Windows because docker-compose is currently not available on Windows.

I am working on a bash script that can be run inside an msys (git-bash) shell that will simulate the critical docker-compose commands.  It will not be driven by the yaml config but should suffice for the purpose.

Opening this ticket for any discussion on the topic.  I will post a link to a draft script once it is ready and will provide a PR once it is functional.

Related note - by default, the boot2docker configuration on Windows only allows mapping of volumes to directories underneath c:\users\ - this should be mentioned in the documentation.  If a similar restriction exists on Mac deployments we should also add that in.

**Comment by msamblanet** [comment]
[Draft script in GitHub Gist](https://gist.github.com/msamblanet/b139499e8296d8fda53d)

**Comment by adalinesimonian** [comment]
[Windows support for `docker-compose`](https://github.com/docker/compose/issues/1085) seems imminent in the upcoming [1.5.0 release](https://github.com/docker/compose/milestones/1.5.0).

Support for attached mode [may not make it into the release](https://github.com/aanand/fig/commit/0d5ad2ca78bea85b021fd3fc84648925f3754070), which in our case is perfectly permissible as we use detached mode (`-d`).

We have several options here:

**1: Patch around not having docker-compose**

**Pros:**
- Immediate support

**Cons:**
- Unsupported solution
- Extra maintenance
- Potentially inconsistent behaviour

**2: Wait for docker-compose 1.5.0**

**Pros:**
- Supported solution  
- Consistent behaviour  
- No extra maintenance

**Cons:**
- Need to wait a short while

Need some input here. What does everyone think?

**Comment by msamblanet** [comment]
The question comes down to how imminent is it (always a challenging question in the modern software world). 

#2 is certainly better for Connect long-term...as long as it comes soon enough for the end-users.

I have my draft script linked above and can maintain it in that separate gist, which Connect could link to for now.  This gives you a short-term solution assuming we trust that 1.5.0 will be out shortly (and will be reasonably stable on Windows).

I will look into pulling a dev build of the docker-connect-windows work and seeing if I can assess stability in the meantime.

**Comment by msamblanet** [comment]
FYI - the pre-release version of docker-compose for Windows can be installed although it is currently broken by [docker-compose-2035](https://github.com/docker/compose/pull/2035)

Once that bug is fixed, then Windows users can install for testing (assuming Python is installed) with:

`pip install --upgrade git+https://github.com/dopry/compose.git@windows`

I will test it out and report back once 2035 is fixed

**Comment by christiansmith** [comment]
Thanks @msamblanet!

**Comment by msamblanet** [comment]
Well good news is I found a commit of the Windows WIP that seems to install and run at least...

[Docker Compose PR 1957](https://github.com/docker/compose/pull/1957)

`pip install --upgrade git+https://github.com/aanand/fig.git@fb304981536722ef42c9688b0688d4be048ccfd1`

Bad news: It fails mapping volumes - added my findings to [this docker-compose issue](https://github.com/docker/compose/issues/2050#issuecomment-141519366)

**Comment by mnowster** [comment]
Hi there, 

I'm a maintainer on docker-compose and saw you linking to here from one of the issues. Thought it might be helpful to let you know that our wiki page contains when we expect to release 1.5, https://github.com/docker/compose/wiki.

We should be cutting a release candidate in the next week or so, you may wish to test against that, as it will contain more fixes for the windows build than just that singular PR you're referencing. If that helps with your decision making.

Thanks for taking the time to file the extra info on the issue :+1:

**Comment by msamblanet** [comment]
Thanks for the info @mnowster - right now I just can't seem to find any single git tag/commit that has all the pieces I need in one place...As of this AM:
- docker/master currently fails with fnctl issues for me despite the fact that docker/compose/
- the latest commit from docker/compose/1957 has not been merged or updated - and last time I tried it, it failed with volume mapping parse issues (see 2 posts above)
- There were some other branches/tags I've tried, all with variations of already reported failures...

I feel for the Connect project, docker-compose it is likely close enough and waiting is best (although it is currently making my personal attempts to run the system harder)...

@mnowster - If you happen to know what the best GIT tag/commit to follow/use for pulling WIP on Docker-Compose for Windows, please let me know...there are a lot of them floating around :)

**Comment by msamblanet** [comment]
With the current docker-compose on master, it is now launching on windows!  I have not done any deeper tests yet but you can now `docker-compose up` and all 3 services startup.

Not sure on the exact release schedule for docker-compose (or a docker-toolbox including it on Windows) but people needing this now can get it by doing a: `pip install --upgrade git+https://github.com/docker/compose.git`

If anybody sees additional Windows specific issues in Compose, please call me out and I will try to help troubleshoot as I can.

And a special thanks to @mnowster for his efforts to make docker-compose work on Windows.

**Comment by christiansmith** [comment]
This is awesome news! Thanks @msamblanet for staying on top of it.
