### ISSUE TITLE
Volume directories not created

### ISSUE THREAD

**Issue by msamblanet** [anvilresearch/connect-cli#31]
When running `nvl init`, the resulting docker-compose.yml references a number of folders for mapping volumes that do not exist.  I believe it would be best if these folders were created by the init process.

If the team agrees, I can provide a PR to add this to the initialization.

**Comment by adalinesimonian** [comment]
What folders in particular seem to be the culprits?

**Comment by christiansmith** [comment]
I'd guess views, email, public, keys... are there more?

**Comment by msamblanet** [comment]
Just did a fresh build - the following volume directories did not exist:
- redis/data
- redis/logs (well this is future for #32)
- connect/email
- connect/protocols
- connect/providers
- connect/public
- connect/views
- nginx/logs

Is it possible these are auto-created by docker-compose?  They were not created by `docker create` or `docker run`...

**Comment by adalinesimonian** [comment]
So the status quo is currently:

| Directory | Why it may not be there by default |
| --- | --- |
| connect/keys | Created in unreleased version of `connect-cli` |
| connect/email | Optional, only necessary if overwriting/adding email templates |
| connect/protocols | Optional, only necessary if overwriting/adding protocol definitions |
| connect/providers | Optional, only necessary if overwriting/adding provider definitions |
| connect/public | Optional, only necessary if overwriting/adding static assets |
| connect/views | Optional, only necessary if overwriting/adding view templates |
| redis/data | ? |
| redis/logs | #32 |
| nginx/logs | #32 |

**Comment by adalinesimonian** [comment]
@christiansmith What's up with redis/data?

**Comment by christiansmith** [comment]
redis/data I believe is created also when the containers are launched by docker compose.

**Comment by christiansmith** [comment]
Given that not everyone using Docker will use Docker Compose, I think we should definitely create the mandatory directories with `nvl init`.

**Comment by msamblanet** [comment]
I'll submit a CR for the "init' command to pre-create all the folders - should be up shortly.  Even if not needed in all cases, it should not hurt.

**Comment by adalinesimonian** [comment]
Fixed by #35
