### ISSUE TITLE
Redis logs volumes not mapped for docker

### ISSUE THREAD

**Issue by msamblanet** [anvilresearch/connect-cli#32]
`nvl init` creates a docker-compose.yml that maps most of the data and config directories for the server components.  HOWEVER, the redis log volume is not mapped.  Given that the nginx log volume is mapped, it would seem to make sense to map this also.

If the team is in agreement, I can provide a PR for this change.

**Comment by christiansmith** [comment]
Please! I've been meaning to get to that.

**Comment by adalinesimonian** [comment]
Fixed by #34
