### ISSUE TITLE
Scoping Docker container names

### ISSUE THREAD

**Issue by msamblanet** [anvilresearch/connect-cli#33]
The container names configured in docker-compose.yml have very generic names.  When I went to install this on my development machine, the container name `redis` and `nginx` would conflict with other general containers I have.  I feel it would be best if connect would prefix the container names with the connect instance name - so if my instance name was "xyzzy", name it "xyzzy_redis"...

WARNING: As docker-compose does not work on Windows - I might be missing something.  If so please correct me so I can ensure my scripts for #29 are consistent with docker-compose behavior.

If this team is in agreement with this, I can provide a PR for this change.

**Comment by adalinesimonian** [comment]
`docker-compose` scopes any containers to the name of the current working directory.

e.g.

```
~/Practice/connect-nv-docker $ docker-compose up -d

Creating connectnvdocker_redis_1...
Creating connectnvdocker_connect_1...
Creating connectnvdocker_nginx_1...

~/Practice/connect-nv-docker $ docker-compose ps

          Name                 Command       State                    Ports                   
---------------------------------------------------------------------------------------------
connectnvdocker_connect_1   node server.js   Up                                               
connectnvdocker_nginx_1     nginx            Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp 
connectnvdocker_redis_1     redis-server     Up      6379/tcp   
```

**Comment by msamblanet** [comment]
OK - didn't realize that - should likely close this item then (adds the _1 also which explains something I had in another issue).

**Comment by adalinesimonian** [comment]
Cool beans! Closing this issue. Feel free to re-open if necessary.
