### ISSUE TITLE
Docker Images - nginx and redis versions not pinned

### ISSUE THREAD

**Issue by msamblanet** [anvilresearch/connect-cli#38]
The `apk add` in both the nginx and redis `dockerfile` do not specify a version.  Should these be pinned to some level to ensure a compatible version?

As an alternative for discussion, is there a reason the official [nginx](https://hub.docker.com/_/nginx/) and [redis](https://hub.docker.com/_/redis/) Docker Hub images are not used instead?  I'm not clear why the team is maintaining it's own images for these components when there are official ones.

In either case, once the team comes to an opinion, I would be happy to provide a PR for either scenario.

**Comment by adalinesimonian** [comment]
We're maintaining our own images because the official ones are a bit heavy-weight. We use Alpine Linux, which has a very small footprint, in the range of a small number of megabytes.

As to why the images aren't pinned to versions, I have a feeling this is an oversight more than anything.

**Comment by christiansmith** [comment]
@msamblanet great catch on the dockerfiles.

@oren turned us on to [Alpine](https://www.alpinelinux.org/), which seems ideal both as a host for this project and as base image for docker containers: 

> "Alpine Linux is a security-oriented, lightweight Linux distribution based on musl libc and busybox."

We reduced the image size by one to two orders of magnitude vs the official images. In theory, there ought to be a smaller surface area as well.

**Comment by msamblanet** [comment]
Closing - was resolved by merge of #40
