### ISSUE TITLE
Missing access token error

### ISSUE THREAD

**Issue by EternalDeiwos** [anvilresearch/connect-cli#61]
Login still works but this seems to happen whenever I try use `nvl client:info` or `nvl client:list`

**Comment by christiansmith** [comment]
I'm sure this is because we went ahead and released the patch for the JWK issue. I'll make an effort to push the new CLI code that works with the new version of connect-nodejs tonight if possible. Still have some work to do before we're ready.

**Comment by christiansmith** [comment]
This should be fixed with the release of 0.1.13. Please upgrade and let me know if it works now :)

**Comment by EternalDeiwos** [comment]
working perfectly, new features are looking quite good as well.

**Comment by christiansmith** [comment]
Thanks!
